return {}
-- return {
--     "ibhagwan/fzf-lua",
--     dependencies = { "nvim-tree/nvim-web-devicons" },
--     opts = {
--         files = {
--             git_icons = false
--         },
--         oldfiles = {
--             include_current_session = true, -- include bufs from current session
--         },
--     },
-- }
